"""Writes src/datafiles.h: path, size and SHA-1 of every game file the port reads (Data, Common, Logo, Game, Music.bf of the
English 1.00 CD, Eko Software 2001, ISO SHA-1 2704de40e06b30546bb2d0e3a1dda7838010aab5). The engine checks a copy of the CD
against it (src/datasetup.c). Only metadata is written, no game content.
Usage: python tools/mkmanifest.py <CD root or a folder with the same layout> [out.h]"""
import hashlib, os, sys

TOPS = ('Data', 'Common', 'Logo', 'Game', 'Music.bf')
root = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src', 'datafiles.h')

files = []
for top in TOPS:
    p = os.path.join(root, top)
    if os.path.isfile(p): files.append(top); continue
    for d, _, fs in os.walk(p):
        files += [os.path.relpath(os.path.join(d, f), root).replace(os.sep, '/') for f in fs]
files.sort(key=str.lower)

rows, total = [], 0
for rel in files:
    h, n = hashlib.sha1(), 0
    with open(os.path.join(root, rel), 'rb') as f:
        for chunk in iter(lambda: f.read(4 << 20), b''): h.update(chunk); n += len(chunk)
    total += n
    rows.append('    { "%s", %du, "%s" },' % (rel, n, h.hexdigest()))

with open(out, 'w', newline='\n') as o:
    o.write('/* datafiles.h - generated by tools/mkmanifest.py, do not edit: the game files of the English 1.00 CD (Woody Woodpecker:\n'
            ' * Escape from Buzz Buzzard Park, Eko Software / Cryo 2001) that the port reads, with their size and SHA-1. Metadata only. */\n')
    o.write('#define DATAFILES_COUNT %d\n#define DATAFILES_BYTES %du\n' % (len(rows), total))
    o.write('static const struct { const char *path; unsigned size; const char *sha1; } k_datafiles[DATAFILES_COUNT] = {\n')
    o.write('\n'.join(rows) + '\n};\n')
print(f'{out}: {len(rows)} files, {total / 2**20:.1f} MB')
