"""Writes src/datafiles.h: path, size and SHA-1 of every game file the port reads (Data, Common, Logo, Game, Music.bf of the
English 1.00 CD, Eko Software 2001, ISO SHA-1 2704de40e06b30546bb2d0e3a1dda7838010aab5), plus, for every other supported
release, the files in which it differs or that it lacks. The engine checks a copy of the CD against it (src/datasetup.c, datasetup_posix.c).
Only metadata is written, no game content.

Usage: python tools/mkmanifest.py <English CD root> ["Label=<root of another release>" ...] [-o out.h]
  e.g. python tools/mkmanifest.py extract "Brazilian Portuguese (Pica-Pau, 2002)=out/builds/br/cd" \
           "Polish (Wielka Draka, 2002)=out/builds/pl/cd" "Spanish (2001)=out/builds/es/cd" "Russian (1C, 2002)=out/builds/ru/cd"
A root is a CD or a folder with the same layout. Releases are matched in the order given. A file a release lacks gets an
entry with size 0 and an empty SHA-1; only list releases whose missing files the port never reads (the Russian CD has no
Data/Lang, the console-only language level)."""
import hashlib, os, sys


HELPERS = r'''/* checks manifest file i (sha1 NULL = by size only): 1 when it is the copy of any supported release, 0 if none. Adds 1 to
 * fit[r] for every release r whose copy it is, so the release a whole copy came from = the r with the highest fit[r]
 * (datafile_best). A release's copy = its k_datafiles_alt entry, or the English file when it has none; an entry with an
 * empty SHA-1 = the release has no such file. */
static int datafile_tally(int i, unsigned long long size, const char *sha1, int *fit)
{
    int any = 0;
    for (int r = 0; r < DATAFILES_RELEASES; r++) {
        unsigned sz = k_datafiles[i].size; const char *h = k_datafiles[i].sha1;
        for (int k = 0; k < DATAFILES_ALT; k++) if (k_datafiles_alt[k].file == i && k_datafiles_alt[k].release == r) { sz = k_datafiles_alt[k].size; h = k_datafiles_alt[k].sha1; }
        if (*h && size == sz && (!sha1 || !strcmp(sha1, h))) { any = 1; if (fit) fit[r]++; }
    }
    return any;
}
/* manifest file i is missing: 1 when a supported release has no such file either (adds 1 to fit[r] for each), 0 if all have it */
static int datafile_absent(int i, int *fit)
{
    int any = 0;
    for (int k = 0; k < DATAFILES_ALT; k++) if (k_datafiles_alt[k].file == i && !*k_datafiles_alt[k].sha1) { any = 1; if (fit) fit[k_datafiles_alt[k].release]++; }
    return any;
}
static int datafile_best(const int *fit) { int b = 0; for (int r = 1; r < DATAFILES_RELEASES; r++) if (fit[r] > fit[b]) b = r; return b; }
'''
TOPS = ('Data', 'Common', 'Logo', 'Game', 'Music.bf')
args = sys.argv[1:]
out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src', 'datafiles.h')
if '-o' in args: i = args.index('-o'); out = args[i + 1]; del args[i:i + 2]
root, releases = args[0], [a.split('=', 1) for a in args[1:]]

files = []
for top in TOPS:
    p = os.path.join(root, top)
    if os.path.isfile(p): files.append(top); continue
    for d, _, fs in os.walk(p):
        files += [os.path.relpath(os.path.join(d, f), root).replace(os.sep, '/') for f in fs]
files.sort(key=str.lower)

def stat(path):
    h, n = hashlib.sha1(), 0
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(4 << 20), b''): h.update(chunk); n += len(chunk)
    return n, h.hexdigest()

rows, total, base = [], 0, []
for rel in files:
    n, h = stat(os.path.join(root, rel)); total += n; base.append((n, h))
    rows.append('    { "%s", %du, "%s" },' % (rel, n, h))

alt = []
for r, (label, rroot) in enumerate(releases, 1):
    for i, rel in enumerate(files):
        p = os.path.join(rroot, rel)
        if not os.path.exists(p): alt.append((i, r, 0, '')); continue
        n, h = stat(p)
        if (n, h) != base[i]: alt.append((i, r, n, h))
    print('%s: %d files differ from the English CD (%d of them missing)' % (label, sum(1 for a in alt if a[1] == r), sum(1 for a in alt if a[1] == r and not a[3])))

with open(out, 'w', newline='\n') as o:
    o.write('/* datafiles.h - generated by tools/mkmanifest.py, do not edit: the game files of the English 1.00 CD (Woody Woodpecker:\n'
            ' * Escape from Buzz Buzzard Park, Eko Software / Cryo 2001) that the port reads, with their size and SHA-1, and the files\n'
            ' * in which the other supported releases differ or that they lack (k_datafiles_alt). Metadata only. */\n')
    o.write('#include <string.h>\n#define DATAFILES_COUNT %d\n#define DATAFILES_BYTES %du\n' % (len(rows), total))
    o.write('static const struct { const char *path; unsigned size; const char *sha1; } k_datafiles[DATAFILES_COUNT] = {\n')
    o.write('\n'.join(rows) + '\n};\n')
    o.write('#define DATAFILES_RELEASES %d\n' % (len(releases) + 1))
    o.write('static const char *const k_releases[DATAFILES_RELEASES] = { "English 1.00 (2001)"%s };\n'
            % ''.join(', "%s"' % l for l, _ in releases))
    o.write('#define DATAFILES_ALT %d\n' % max(1, len(alt)))
    o.write('static const struct { unsigned short file, release; unsigned size; const char *sha1; } k_datafiles_alt[DATAFILES_ALT] = {\n')
    o.write('\n'.join('    { %d, %d, %du, "%s" },   /* %s */' % (i, r, n, h, files[i]) for i, r, n, h in alt) or '    { 0xffff, 0, 0, "" }')
    o.write('\n};\n')
    o.write(HELPERS)
print(f'{out}: {len(rows)} files, {total / 2**20:.1f} MB, {len(alt)} alternative entries')
