/* datafiles.h - generated by tools/mkmanifest.py, do not edit: the game files of the English 1.00 CD (Woody Woodpecker:
 * Escape from Buzz Buzzard Park, Eko Software / Cryo 2001) that the port reads, with their size and SHA-1, and the files
 * in which the other supported releases differ or that they lack (k_datafiles_alt). Metadata only. */
#include <string.h>
#define DATAFILES_COUNT 232
#define DATAFILES_BYTES 668367749u
static const struct { const char *path; unsigned size; const char *sha1; } k_datafiles[DATAFILES_COUNT] = {
    { "Common/Knothead.rck", 5569286u, "cafbfdb6be8426573bd6af5503978b47efe2963f" },
    { "Common/Splinter.rck", 5503712u, "9f8b33e948b85b14612bbd6f11c8b9eb7a12ef34" },
    { "Common/Woody.rck", 5756428u, "abd196c6d19e092306443aa2452b5ed945bb39b6" },
    { "Data/Blackbox/Blackbox.col", 200u, "c45d01b195decd87a0bf097784fba6734005b8ea" },
    { "Data/Blackbox/Blackbox.gel", 12868u, "ed73b9b046bb7f77a10db5852b4616b25ce28a75" },
    { "Data/Blackbox/Blackbox.ins", 2268072u, "4adfde8d8a9e099366d113e371bbc12dcae3ef7d" },
    { "Data/Blackbox/Blackbox.lit", 20u, "3bc67ec8c96da9b3f613e12a1958983ef9b89968" },
    { "Data/Blackbox/Blackbox.rck", 6490818u, "c12d6cf71f88826c83e8c1d7c688ee56bb0376da" },
    { "Data/Blackbox/Blackbox.tex", 43456u, "33b72d962ab489dbcc04dbdc01f8fdd6768d0a0c" },
    { "Data/Blackbox/Blackbox.vis", 24u, "8577db60b531ff5e9142f6665d1b781ea4ab56fe" },
    { "Data/Blackbox/code", 132u, "49a61b3054e4c624bc4b98f7fd3a8caa3d0dfbb5" },
    { "Data/Credits/code", 132u, "26a305a33719852652b4ce4b62d52f3677ed651c" },
    { "Data/Credits/Credits.col", 256u, "b376885ac8452b6cbf9ced81b1080bfd570d9b91" },
    { "Data/Credits/Credits.gel", 17032u, "15ef76856f8720b2a52625dcf075e12e5f4b7a4e" },
    { "Data/Credits/Credits.ins", 2268072u, "c1f3b26a3dcce37a68feded5a52aae96f4146a5b" },
    { "Data/Credits/Credits.lit", 20u, "3bc67ec8c96da9b3f613e12a1958983ef9b89968" },
    { "Data/Credits/Credits.rck", 3811706u, "df8863b990d73fb2f9e3df6f2558b95f38d2ecb7" },
    { "Data/Credits/Credits.tex", 43456u, "528a9fd1a39c6787d5a1ece31e712d8da6dd662b" },
    { "Data/Credits/Credits.vis", 24u, "8577db60b531ff5e9142f6665d1b781ea4ab56fe" },
    { "Data/House/code", 8632u, "eb702e652718691184973e0bf5b1ea4dc9792ab1" },
    { "Data/House/House.col", 10980u, "38086a4d96dd9cbd384e059b0470cdce4509117d" },
    { "Data/House/House.gel", 825772u, "b9e55b4f40159691909b6ace12a2d73362cf5672" },
    { "Data/House/House.ins", 7189676u, "9179fc2afffa470b432b8c1948710262557a0514" },
    { "Data/House/House.lit", 270860u, "298800ced745ebc313c7c21c2e0cd7e9feee16ba" },
    { "Data/House/House.rck", 1377896u, "9c5b475aab2b5aea07680e10aff20ce5f1fdc036" },
    { "Data/House/House.tex", 4186404u, "44061363c06f28b1eb98e14244de6f4e2972c945" },
    { "Data/House/House.vis", 5904u, "d230853c2b38c6f8c2907eeb8f5232f55469c946" },
    { "Data/K1A/code", 63876u, "ca4c444aae931fe8d2d9ef8a4f1796506a2f024b" },
    { "Data/K1A/K1A.col", 74968u, "139890a92cc4e8bff3582d6f7317843b179dab12" },
    { "Data/K1A/K1A.gel", 2714108u, "583e0b59ecd3972ccf623636fb6b6e445e279a91" },
    { "Data/K1A/K1A.ins", 2851944u, "80379a3da6b0b690e6e31e7af6742e03ac19d3e0" },
    { "Data/K1A/K1A.lit", 471384u, "a6b9be0946212f98bc3ce086c83d3234fac6dd0d" },
    { "Data/K1A/K1A.rck", 2085118u, "2360ffa9b4ecf8ebb0c4995e2a55501bf3b467c4" },
    { "Data/K1A/K1A.tex", 4052044u, "35bfaa915a15618bf2257998d0bb4d9f649a8265" },
    { "Data/K1A/K1A.vis", 29776u, "e1d884de72c3dadb78f9f48f813a765afb80fc0c" },
    { "Data/K1R/code", 33640u, "8b65c3d05eb84f3cf1299915e2d91c74173a7a7f" },
    { "Data/K1R/K1R.col", 56012u, "0a29e13bcb10e8cb940a635c59d501d60321b287" },
    { "Data/K1R/K1R.gel", 2408708u, "b50efff1c8516eb35c131d53d9e952f1a3b287d7" },
    { "Data/K1R/K1R.ins", 1088880u, "41b56c950424939db1171f3f4f4ad8d0d89d70c9" },
    { "Data/K1R/K1R.lit", 307584u, "e3f64d0046a61b2d790ed103fdd864c8d92dc044" },
    { "Data/K1R/K1R.rck", 1045196u, "374d076f16b68cc9993347819df9675779e095a8" },
    { "Data/K1R/K1R.tex", 4103232u, "6be76338eff65326f0c9221801a771897011aeb4" },
    { "Data/K1R/K1R.vis", 50304u, "e1cbb07b660d39365a938b3a4e73f99bf6af8b01" },
    { "Data/K2A/code", 75048u, "f77a0d9f4214f141844396f9fafa5174d13ce04c" },
    { "Data/K2A/K2A.col", 50016u, "d54f153c06d5cd5e13e65a70f18da0b24dd30806" },
    { "Data/K2A/K2A.gel", 1208972u, "a49adfadb3096c7f4fe03af9a61dc80db3858938" },
    { "Data/K2A/K2A.ins", 3057680u, "fbdcefb11b0754114c01a338d23f9ebc3f921727" },
    { "Data/K2A/K2A.lit", 405556u, "af142455bbbb7ca24854d0b6ce4506b14e54f59b" },
    { "Data/K2A/K2A.rck", 3153810u, "055e39af1e8f673df69c6895d3abbe185876f18c" },
    { "Data/K2A/K2A.tex", 4212564u, "16347f4dce7c54bd657595cba41efdc64c26a08b" },
    { "Data/K2A/K2A.vis", 21024u, "e39566fc3b7b8a0ac60bf9cb4d45ee25e58c1398" },
    { "Data/K2R/code", 50892u, "0955e559430085fc2bb730c959b884d2ea882983" },
    { "Data/K2R/K2R.col", 43460u, "191de04e34a6a7c45a712e079d4da89aef20cef2" },
    { "Data/K2R/K2R.gel", 1349228u, "26230e551814f55becebb104c1ead5d2b5ae9ea9" },
    { "Data/K2R/K2R.ins", 1303436u, "f8d407ae77876ffd1d4e29c86259e1e1958c4bee" },
    { "Data/K2R/K2R.lit", 318204u, "ad77c04125a0377c5ac9b9f951491d4772b8dc55" },
    { "Data/K2R/K2R.rck", 1300228u, "70b849a4cbfd773b4672d17524132aa5c05862f5" },
    { "Data/K2R/K2R.tex", 3510684u, "b1fbf8b16453ca92ed7aed9751b87c4850e78c20" },
    { "Data/K2R/K2R.vis", 13072u, "2f36ec57267c5a4fec58d49def08a7f1358852eb" },
    { "Data/K3A/code", 85464u, "f4358476496dbd5d9cece73f463a5a0172ec5659" },
    { "Data/K3A/K3A.col", 114300u, "8d5a7151dbf9af8348020adc17dec242d9839fb1" },
    { "Data/K3A/K3A.gel", 2804052u, "1344b8bd20a95740c069f24188062270a331b17f" },
    { "Data/K3A/K3A.ins", 3604092u, "52bd29ff99618a6e0da6c3d562f789f904938cc2" },
    { "Data/K3A/K3A.lit", 840348u, "be618c1c440a2bbc0ca8972e6e59b75c53c5c8fd" },
    { "Data/K3A/K3A.rck", 2106900u, "b21c53024b210f11a89f308ed41a7d9e8637fda8" },
    { "Data/K3A/K3A.tex", 4511380u, "62e958f44623671f03a14840617d7744543e1a22" },
    { "Data/K3A/K3A.vis", 35704u, "3555db0c5ce889b20a4e5722c78714fc5155cd07" },
    { "Data/K3R/code", 35412u, "0667a24e1ab920df86f9688a69d4b76d141bc738" },
    { "Data/K3R/K3R.col", 47108u, "123da6b5d7279c62351f420c0b35e6886957be84" },
    { "Data/K3R/K3R.gel", 1925652u, "95df7349690ad65c51f82ac257da63ad1f811687" },
    { "Data/K3R/K3R.ins", 1778576u, "d63f9d0924f48d5a591f5a109762ba2620fbcce6" },
    { "Data/K3R/K3R.lit", 320948u, "8ba186545beab935875ec036a44534ac8175c91f" },
    { "Data/K3R/K3R.rck", 788042u, "d838cbf7ae120e35891979eb251e0af8e62c132a" },
    { "Data/K3R/K3R.tex", 3963428u, "ce89187be9e14560a329064ca8e096e52405f0b3" },
    { "Data/K3R/K3R.vis", 32800u, "cc0a045e6f23303a2c24b4b4d203eba3bdafb8f7" },
    { "Data/KWS/code", 41924u, "4e54f086936117633a802d9f365f472a0808fc16" },
    { "Data/KWS/KWS.col", 86236u, "48b39dcae58c9a6d0fb266da8ab08c14c7261466" },
    { "Data/KWS/KWS.gel", 2145804u, "8f38963fdc94200224124fc7afd875ba5216f617" },
    { "Data/KWS/KWS.ins", 2964028u, "cf6961e7531a77fed9f2433db5e60cc2163e09cf" },
    { "Data/KWS/KWS.lit", 603692u, "0e77e61f82796b1ff41e4ed8d4f92811f8db09ed" },
    { "Data/KWS/KWS.rck", 2336506u, "85cd5319a94f8fc7b58339bebe6a35b060ad5a35" },
    { "Data/KWS/KWS.tex", 4169788u, "5f943f49a19d7f45efd5f7594bfdc4c2bcadaa37" },
    { "Data/KWS/KWS.vis", 45792u, "e41249765d3aa3a8a79d2913efe2bf0a64584e13" },
    { "Data/Lang/code", 108u, "c1eccf48254403b04a9a361c478bc588a56b902d" },
    { "Data/Lang/Lang.col", 200u, "c45d01b195decd87a0bf097784fba6734005b8ea" },
    { "Data/Lang/Lang.gel", 12868u, "776e65777c6bdaddbf0e55a49fc0234cfe635079" },
    { "Data/Lang/Lang.ins", 2268072u, "e926a4b834e8ff74ff60474477d017e590531a86" },
    { "Data/Lang/Lang.lit", 20u, "3bc67ec8c96da9b3f613e12a1958983ef9b89968" },
    { "Data/Lang/Lang.rck", 1377944u, "341d45ff3ed9d8960fd490cb4e25be3809888b35" },
    { "Data/Lang/Lang.tex", 43456u, "2105cbc65a9b41e9b1ab6bb2cb849385bf897fb6" },
    { "Data/Lang/Lang.vis", 24u, "8577db60b531ff5e9142f6665d1b781ea4ab56fe" },
    { "Data/S1A/code", 69588u, "f881b7e3b4de6ab79d7726ae483b3f07aeb7df0b" },
    { "Data/S1A/S1A.col", 73804u, "7db81b7f84f5d62e31a607f2e27e4d04c2385c68" },
    { "Data/S1A/S1A.gel", 2714108u, "583e0b59ecd3972ccf623636fb6b6e445e279a91" },
    { "Data/S1A/S1A.ins", 2874920u, "730dc7dd7ba365db169473c534699efc3d741355" },
    { "Data/S1A/S1A.lit", 471384u, "a6b9be0946212f98bc3ce086c83d3234fac6dd0d" },
    { "Data/S1A/S1A.rck", 2085118u, "12cfabb4eddfed54bfed52ba6a7f642d924338e8" },
    { "Data/S1A/S1A.tex", 4060300u, "b2d98abde8bbfa64275b76680c3dfebd83fd78ab" },
    { "Data/S1A/S1A.vis", 29776u, "e1d884de72c3dadb78f9f48f813a765afb80fc0c" },
    { "Data/S1R/code", 34768u, "ef9628e4b5fa44cef6214c92534a46f0f730a0b6" },
    { "Data/S1R/S1R.col", 44508u, "dbb85febc94801cfa9d9b639338d22b6fb53a4b3" },
    { "Data/S1R/S1R.gel", 2408708u, "b50efff1c8516eb35c131d53d9e952f1a3b287d7" },
    { "Data/S1R/S1R.ins", 1075088u, "ab58fe18e35ae2452fab10802e78a5f011ed013e" },
    { "Data/S1R/S1R.lit", 307584u, "99490e54f3c1010b4a4104ba7f1dc3b74a074475" },
    { "Data/S1R/S1R.rck", 1045196u, "4227e79fe9c890e9254830094da36a8ee713c5ec" },
    { "Data/S1R/S1R.tex", 3867924u, "89431c7b2d7db511925960875b25f9b99559c789" },
    { "Data/S1R/S1R.vis", 50304u, "e1cbb07b660d39365a938b3a4e73f99bf6af8b01" },
    { "Data/S2A/code", 71520u, "6013e01ef7873a08354f710c3278373098ba0d3f" },
    { "Data/S2A/S2A.col", 47132u, "84410fefca79114f157fdf9cd5daaef4db8364a5" },
    { "Data/S2A/S2A.gel", 1208972u, "c9f622daa5de9835a3ef0d41504b1ae81c21dc37" },
    { "Data/S2A/S2A.ins", 2953396u, "c74feb1366fe6fa5d6038b1b93c603e16580663d" },
    { "Data/S2A/S2A.lit", 405556u, "af142455bbbb7ca24854d0b6ce4506b14e54f59b" },
    { "Data/S2A/S2A.rck", 3153810u, "3207ab212dcb4ec82479a6e80616c2cea497195e" },
    { "Data/S2A/S2A.tex", 4206532u, "0b8b6dfbb30ad55ad403565b3138cd76471690e0" },
    { "Data/S2A/S2A.vis", 21024u, "e39566fc3b7b8a0ac60bf9cb4d45ee25e58c1398" },
    { "Data/S2R/code", 38880u, "9acc4457397ea517d3df803b5d34784fced6ce0d" },
    { "Data/S2R/S2R.col", 36876u, "889a6c8ee3e231e678fb128cebb766ca9d0bf43b" },
    { "Data/S2R/S2R.gel", 1349228u, "26230e551814f55becebb104c1ead5d2b5ae9ea9" },
    { "Data/S2R/S2R.ins", 1182320u, "45c3e34c94df4130288192551c400cb225f3ccd0" },
    { "Data/S2R/S2R.lit", 318204u, "b9cd9059a2c1c696f5877cd98e6082d1f913e5cd" },
    { "Data/S2R/S2R.rck", 1300228u, "c8ffd4a8c96baf14f396f8b8bf34bdcb63673949" },
    { "Data/S2R/S2R.tex", 3492736u, "769d320d9a637bfeb99e576b0339d8d53a4566c5" },
    { "Data/S2R/S2R.vis", 13072u, "2f36ec57267c5a4fec58d49def08a7f1358852eb" },
    { "Data/S3A/code", 88104u, "62b2843433799a3cbc157da6143c16b3ed086b5b" },
    { "Data/S3A/S3A.col", 112060u, "c71622b1f76139f5ba7825070ac0d2f80798b489" },
    { "Data/S3A/S3A.gel", 2804052u, "9fc68ec268763121f40ba6c8c0d42ef5736d9872" },
    { "Data/S3A/S3A.ins", 3440176u, "df11a2ef4b0f5f90378fba9b1c5a7b56ad07dd41" },
    { "Data/S3A/S3A.lit", 840348u, "72a14e32ded9aed87c577ce706c82a3bfc09ce6b" },
    { "Data/S3A/S3A.rck", 2106900u, "ee0f972c496fdbc95dfc8b0e4544f33d1c126837" },
    { "Data/S3A/S3A.tex", 4427832u, "332bbf0fa30cb07dfcd62984bfe65ce700ef7fbc" },
    { "Data/S3A/S3A.vis", 34008u, "90f44d6e27ea3dbd5f1dcf77c978afc1e88572a1" },
    { "Data/S3R/code", 24468u, "1e88055a5246a0da4b024610ce6ca185ca7412e0" },
    { "Data/S3R/S3R.col", 40368u, "2f40135b6b72987400247c7561ee172a8e01b687" },
    { "Data/S3R/S3R.gel", 1925652u, "95df7349690ad65c51f82ac257da63ad1f811687" },
    { "Data/S3R/S3R.ins", 1540552u, "7e48cd20f868eb0cb76ff9a65cc55eeca0abf9db" },
    { "Data/S3R/S3R.lit", 320948u, "4a1fc9888160a38af4306e33c175294ebecc39e0" },
    { "Data/S3R/S3R.rck", 788042u, "ca2b63011261502a7889637d99451c0892ba97e3" },
    { "Data/S3R/S3R.tex", 4169120u, "e8346e5ccbaa6762036f4bb0ea817f1a55ec7d24" },
    { "Data/S3R/S3R.vis", 32800u, "cc0a045e6f23303a2c24b4b4d203eba3bdafb8f7" },
    { "Data/SWS/code", 41748u, "5ada85147b428f377ef97b71818f1f5da1401094" },
    { "Data/SWS/SWS.col", 86280u, "3e597503219ae01623846dcbef56e833ef9d399e" },
    { "Data/SWS/SWS.gel", 2145804u, "8f38963fdc94200224124fc7afd875ba5216f617" },
    { "Data/SWS/SWS.ins", 2897440u, "8e7dda92d56a7518b4bb5da6109c5208762b17f5" },
    { "Data/SWS/SWS.lit", 603692u, "0e77e61f82796b1ff41e4ed8d4f92811f8db09ed" },
    { "Data/SWS/SWS.rck", 2347130u, "b063f3b875a9fb5704af0e68c869d1104306dac3" },
    { "Data/SWS/SWS.tex", 4176344u, "226340dd8ab1074e8ab50444627cad987089b91f" },
    { "Data/SWS/SWS.vis", 45792u, "e41249765d3aa3a8a79d2913efe2bf0a64584e13" },
    { "Data/W1A/code", 68584u, "d1d2613096e11703001ba9541ea3b688f67f8b05" },
    { "Data/W1A/W1A.col", 75472u, "29fad083e5f242128f69303895800bc6e48a926d" },
    { "Data/W1A/W1A.gel", 2714108u, "9ef775ea2ad338176991884f1cd941fe96be4380" },
    { "Data/W1A/W1A.ins", 3980016u, "cc14de5c4201729a2b7112010c4c1fff38998787" },
    { "Data/W1A/W1A.lit", 471384u, "d7557da9571115496cff39744231fb3151d9fde0" },
    { "Data/W1A/W1A.rck", 2085118u, "2d9cc65e18f52a15e6de89ea1005d02751af250e" },
    { "Data/W1A/W1A.tex", 3882920u, "fc61e9386811cdc72eedbef95ce6cdb484da014e" },
    { "Data/W1A/W1A.vis", 29568u, "814decce12241798d20672a157b01e15b2528345" },
    { "Data/W1B/code", 84968u, "689305b088730d7b399ea9419117c191081c0bad" },
    { "Data/W1B/W1B.col", 71696u, "8836481494f3c2704f4419098abe11ebcdb06b06" },
    { "Data/W1B/W1B.gel", 2260572u, "50273a50de5d0162e6dd697693e045b3c20a5ba2" },
    { "Data/W1B/W1B.ins", 4288788u, "f30b93d416789d8ce21ea0f7cd884531975d10c6" },
    { "Data/W1B/W1B.lit", 738096u, "9fc146da6710b10715e43cb131296dfcd223d171" },
    { "Data/W1B/W1B.rck", 2085118u, "1141c4d6efb4ce3d4d50ab6e922e89ab1f1d5f67" },
    { "Data/W1B/W1B.tex", 3971508u, "a723ef89659f3e3e9beec53b457cff2faf079a94" },
    { "Data/W1B/W1B.vis", 28944u, "b6db25651cf0d4438d2908e4cda81ee69ecc3bc9" },
    { "Data/W2A/code", 82500u, "537ce6b900f3b8a26b38af1437b9f26b5c4e1459" },
    { "Data/W2A/W2A.col", 47700u, "565ae27ae0cbe0738f4e3ae8cda2ed1f1a7ad184" },
    { "Data/W2A/W2A.gel", 1208972u, "030b36841c2939afa5e2b7dc9c74e681c2ae58c2" },
    { "Data/W2A/W2A.ins", 3216120u, "9cb9a2160bae667e343e4230f7961e7d8a45f21a" },
    { "Data/W2A/W2A.lit", 405556u, "af142455bbbb7ca24854d0b6ce4506b14e54f59b" },
    { "Data/W2A/W2A.rck", 3153810u, "f6bfc2fa7b510e8d60bdc64f160f9e175317fd54" },
    { "Data/W2A/W2A.tex", 3930840u, "f31ff67ffe9598299d61020c8333c85cd035e0b8" },
    { "Data/W2A/W2A.vis", 21120u, "0fb7e0d65ffa530a59a8ed472d30a6cd1401e2b8" },
    { "Data/W2B/code", 72332u, "a3e5f7aa71bd0c5617e672781a95c9a47a30884c" },
    { "Data/W2B/W2B.col", 109740u, "2521660215f0003db005f02b4b29c87a46b21c82" },
    { "Data/W2B/W2B.gel", 2390544u, "5de4a24bb796f1ac879fa1811bef27d56598428a" },
    { "Data/W2B/W2B.ins", 4256392u, "45d6b745119f19cb9b89eede01e888176f5f838e" },
    { "Data/W2B/W2B.lit", 653528u, "292b9f953d36c48be5c9d2e034a7494aec5e116b" },
    { "Data/W2B/W2B.rck", 2316056u, "4ee1ac8b0b033b31a6c697e806be05601cf482f0" },
    { "Data/W2B/W2B.tex", 3533768u, "421c70b39816b840da4f2cb30dde04ef665babf8" },
    { "Data/W2B/W2B.vis", 39536u, "a5c1d5b735db57d3c862cccf1206a3dbc03323be" },
    { "Data/W2D/code", 117256u, "2811ab9837587fc4ff61bfc2c88ac103c05a826c" },
    { "Data/W2D/W2D.col", 163624u, "32ec9d6948d716e310f1a676cc39f1c23f68ffdf" },
    { "Data/W2D/W2D.gel", 2479656u, "f8a62b239ef2de8c22b756590d541f975d8c0c64" },
    { "Data/W2D/W2D.ins", 4611164u, "123acffc97ba8051515db01d886ac0d322b8cef9" },
    { "Data/W2D/W2D.lit", 483848u, "785429f3e4ecf177b9f654da3286b96881749138" },
    { "Data/W2D/W2D.rck", 2222362u, "970083fe35920214c1b95ef23add8ebf0c10ab10" },
    { "Data/W2D/W2D.tex", 3422328u, "dc5c45ffef878c43c87c7413fa86b256456a983c" },
    { "Data/W2D/W2D.vis", 29736u, "f898df4405fa3bf96b7c3f3b68a70266421e516b" },
    { "Data/W3A/code", 94692u, "bf3688510f50503bc9f530edd50317bca7243daf" },
    { "Data/W3A/W3A.col", 115284u, "f76ed1bb9135c54798c2c4d27e137ab09b44c128" },
    { "Data/W3A/W3A.gel", 2804052u, "cef293b03d5042be8bbc53de240cdb8d4c734fa5" },
    { "Data/W3A/W3A.ins", 3729940u, "185b6d60e88094a79b5586826d93d11aa2c5fa80" },
    { "Data/W3A/W3A.lit", 840348u, "31c726fa01a2ee179e240be65fccbcc91d75e2f3" },
    { "Data/W3A/W3A.rck", 2106900u, "92262cb4cfc978e11c44cf3bb462001d58063e3f" },
    { "Data/W3A/W3A.tex", 4074824u, "87a1908b983ef0de3cf227dd224b6ee9c9545691" },
    { "Data/W3A/W3A.vis", 35672u, "2a4e95d20b7a62122df6854393b79eefe39b29d5" },
    { "Data/W3B/code", 117512u, "025983065a44e7b3d46393f458adae85f1d946de" },
    { "Data/W3B/W3B.col", 186512u, "2a2f3da8cab793e1df246087cf1748de8e4b822a" },
    { "Data/W3B/W3B.gel", 3183612u, "8fd57071d62c319393927bdbb84a2f97e9ae7f0b" },
    { "Data/W3B/W3B.ins", 4558668u, "ecd04185397d5cc3d2cf3e903604ad48615f7cb7" },
    { "Data/W3B/W3B.lit", 396552u, "39310061bee2e290caeba5acc3e9ac4a08603b7f" },
    { "Data/W3B/W3B.rck", 1888750u, "d9609a3077aa1a57b7334227f76250a03dbf7486" },
    { "Data/W3B/W3B.tex", 3746692u, "f58dc95bd866ec383649e6389f36402b56de1a07" },
    { "Data/W3B/W3B.vis", 62328u, "5dd8ffbd3df60f631dd8160400768ed908f881ac" },
    { "Data/W3C/code", 123116u, "860c17f99a15e770265d51979918936eca477400" },
    { "Data/W3C/W3C.col", 184532u, "d355215ae426060fb30f0ce3627c4630bffd073e" },
    { "Data/W3C/W3C.gel", 2747964u, "a1075d0d24d4c912873ef272ed7d1992dff5253c" },
    { "Data/W3C/W3C.ins", 3196564u, "6d52450926f7a43bfde42fd823bdd239d8d3d21b" },
    { "Data/W3C/W3C.lit", 901032u, "8f9ac86b4557c13dce766fe00776017f95573657" },
    { "Data/W3C/W3C.rck", 2352522u, "689516dfb6526b963c1c623430b8f0f7123f0a5a" },
    { "Data/W3C/W3C.tex", 3719848u, "24bea7331994beeda32d231a7df7c08abdbd6c48" },
    { "Data/W3C/W3C.vis", 39584u, "b27fc153d0127928216871e3bb92caab3620904c" },
    { "Data/W3D/code", 147912u, "4ff00aaa16f6d80b52203d153d0bca99632d96ee" },
    { "Data/W3D/W3D.col", 113076u, "470dfeca9df9f5acdd4ec5eb587c3b40d58769fa" },
    { "Data/W3D/W3D.gel", 2717820u, "5e79f9ff441e5151c0e24483f46bad9f150071f6" },
    { "Data/W3D/W3D.ins", 4923980u, "c65cafa3a4f6048f67a92816854b75aacc070c4f" },
    { "Data/W3D/W3D.lit", 815652u, "4b6418295fc250af652d98fb57639936bfa6b004" },
    { "Data/W3D/W3D.rck", 1895712u, "52498360c84cd7cd5647dc8b53aed87e423979bd" },
    { "Data/W3D/W3D.tex", 4427732u, "dc486bb91ab030f72da63dcd45f2385164a33677" },
    { "Data/W3D/W3D.vis", 28432u, "39743aa56d9e506a66fede07627dae844a0e13f2" },
    { "Data/WWS/code", 66488u, "70ddd393218ae6f3c17910e55bc767841744fb77" },
    { "Data/WWS/WWS.col", 95100u, "8c9567d3a69b57ece2ad46c4871d3f090cc59d1c" },
    { "Data/WWS/WWS.gel", 2145804u, "8f38963fdc94200224124fc7afd875ba5216f617" },
    { "Data/WWS/WWS.ins", 4238724u, "4b9f55d3c9b213e803939f8305f6735dee95cad0" },
    { "Data/WWS/WWS.lit", 603692u, "6d65ef14e52d2572f30830dd05bb946dfcbd31e5" },
    { "Data/WWS/WWS.rck", 2342738u, "607242028e22c05fb04139922da127d6c6423c07" },
    { "Data/WWS/WWS.tex", 3904900u, "37dc6ebc975dbb7bdc3efe20ff3cbcfff3f7f0d9" },
    { "Data/WWS/WWS.vis", 45792u, "e41249765d3aa3a8a79d2913efe2bf0a64584e13" },
    { "Game/mask.bin", 786432u, "7d11cedc08f98d2a3791419611471e9df5321666" },
    { "Logo/Cryo.hnm", 7612740u, "ebbec381457c27a5c7c85325ec4c81790e7accf7" },
    { "Logo/Eko.hnm", 3394352u, "e5a75580a2553eb7f62e05aa5e8eb1a7a36d6145" },
    { "Logo/Universal.hnm", 11887544u, "0f5d1dc2a85585c3af06568b6109df7911fd5045" },
    { "Music.bf", 306844901u, "010c08ada9734b2dc091f7462cb68b8b12422227" },
};
#define DATAFILES_RELEASES 5
static const char *const k_releases[DATAFILES_RELEASES] = { "English 1.00 (2001)", "Brazilian Portuguese (Pica-Pau, 2002)", "Polish (Wielka Draka, 2002)", "Spanish (2001)", "Russian (1C, 2002)" };
#define DATAFILES_ALT 282
static const struct { unsigned short file, release; unsigned size; const char *sha1; } k_datafiles_alt[DATAFILES_ALT] = {
    { 0, 1, 5570022u, "e9f06580a66b24c885d60340741435b8a73f947e" },   /* Common/Knothead.rck */
    { 1, 1, 5504448u, "8b92167e4fd925a22e7484c40ea908176ab4fd03" },   /* Common/Splinter.rck */
    { 2, 1, 5757164u, "247d0b7a70b55de989e931c953c23cd6caa11e70" },   /* Common/Woody.rck */
    { 7, 1, 6491078u, "82adfc64d899edc83e1fe2497df7bc260d3eaec5" },   /* Data/Blackbox/Blackbox.rck */
    { 16, 1, 4074066u, "043c21b20d5d0d2b5faeb611eb905541cfdd8f73" },   /* Data/Credits/Credits.rck */
    { 22, 1, 7189676u, "d7dd6c97f5b6f13b6d44e097e5046a811ba10373" },   /* Data/House/House.ins */
    { 24, 1, 1378156u, "2ca52552517b4dd2d1a38e89aff2749f3d3a925d" },   /* Data/House/House.rck */
    { 27, 1, 64136u, "0859b5de3426d9cce209a80448c27b9a101c876c" },   /* Data/K1A/code */
    { 28, 1, 79356u, "d0afd62bcf31ee2baf7e0ddc8275f71bdd6af89c" },   /* Data/K1A/K1A.col */
    { 30, 1, 2869404u, "7df363cb6202714407eb435178ec13f169a3ef2e" },   /* Data/K1A/K1A.ins */
    { 32, 1, 2085378u, "a548f7aff066bd4d4d0b84ecadbf80136d618def" },   /* Data/K1A/K1A.rck */
    { 33, 1, 4081776u, "2dae7e5729b1e9db4419944028a2377036ccdcdb" },   /* Data/K1A/K1A.tex */
    { 38, 1, 1088880u, "63badcfd880fc32db9fbf91ca0145a1346584c13" },   /* Data/K1R/K1R.ins */
    { 40, 1, 1045456u, "a84d7e31a146377d7c179085ffd507cb269d1237" },   /* Data/K1R/K1R.rck */
    { 46, 1, 3057680u, "ccfd1b19e0048b8049fc50dfac17d8346bdc26ab" },   /* Data/K2A/K2A.ins */
    { 48, 1, 3154070u, "69ef33cf8e3e00239c752bccfc397e1191f5dac5" },   /* Data/K2A/K2A.rck */
    { 54, 1, 1303436u, "84061465dae57d3a4136838138674834bbcaac78" },   /* Data/K2R/K2R.ins */
    { 56, 1, 1300488u, "9c4319d3b61b03268e2d4b629ba993b08b6f0a58" },   /* Data/K2R/K2R.rck */
    { 62, 1, 3604092u, "bb0cf977a246cafb4115a070ef721b21156b02f7" },   /* Data/K3A/K3A.ins */
    { 64, 1, 2107160u, "9430fd6016f900cf598ad2dbd7f9216422c313b2" },   /* Data/K3A/K3A.rck */
    { 70, 1, 1778576u, "ac4210bb54f1d1c8016ca0b1c7e3ef8866856c3a" },   /* Data/K3R/K3R.ins */
    { 72, 1, 788302u, "5127d6345dfc79a0624d632ba793ba863906fae3" },   /* Data/K3R/K3R.rck */
    { 75, 1, 41984u, "6b15c35ac7062317afbcc3414d06ff2e81e23d74" },   /* Data/KWS/code */
    { 76, 1, 87664u, "d17a446526017eb9e7ab551b342ae07d80dd10e5" },   /* Data/KWS/KWS.col */
    { 78, 1, 2964184u, "c005be09ffe5015fd2a86b7929447e174461ea6f" },   /* Data/KWS/KWS.ins */
    { 79, 1, 603364u, "b285074394a2651ea8af24e230cf66c6015b8e28" },   /* Data/KWS/KWS.lit */
    { 80, 1, 2336766u, "657b66755dea175da8eee5e749337f693caa8d93" },   /* Data/KWS/KWS.rck */
    { 81, 1, 4169788u, "73f4a7a245fb0ed0812722706e7ac87d61c0b4d7" },   /* Data/KWS/KWS.tex */
    { 88, 1, 1378204u, "1a39bb51fcaee5a88ab9c3cb86ead566d8ceb499" },   /* Data/Lang/Lang.rck */
    { 89, 1, 43456u, "33b72d962ab489dbcc04dbdc01f8fdd6768d0a0c" },   /* Data/Lang/Lang.tex */
    { 91, 1, 69628u, "1d96e15158750b265c2b3a6e2f8dd0486f2f0754" },   /* Data/S1A/code */
    { 94, 1, 2874920u, "4dd591bd662fe6f36a7d361f6f18f63a18a15774" },   /* Data/S1A/S1A.ins */
    { 96, 1, 2085378u, "200a2bb14d488f86a461c4e962e40faca92fef6d" },   /* Data/S1A/S1A.rck */
    { 102, 1, 1075088u, "d13bec7f00de798319e75792d910a54a290e7d26" },   /* Data/S1R/S1R.ins */
    { 104, 1, 1045456u, "4814b5a51582bb766a9dc09eaf738cccd5f84c9c" },   /* Data/S1R/S1R.rck */
    { 110, 1, 2953396u, "697bfe06c259aed488e61c4d2a6b4439699c4c75" },   /* Data/S2A/S2A.ins */
    { 112, 1, 3154070u, "5e9d8675856611f7aaf737b90ffaa630e36bb6ad" },   /* Data/S2A/S2A.rck */
    { 118, 1, 1182320u, "6975af11183e84dc2d8d382e5a216c79cc51ba07" },   /* Data/S2R/S2R.ins */
    { 120, 1, 1300488u, "a43686fd33438a94d2983ccf9b09cfabbcae94aa" },   /* Data/S2R/S2R.rck */
    { 126, 1, 3440176u, "f030f89b26a3683254e69068ed7d41c3013b3cd0" },   /* Data/S3A/S3A.ins */
    { 128, 1, 2107160u, "83a337321c37f7ab7c5203f448b8af96ea780c4a" },   /* Data/S3A/S3A.rck */
    { 134, 1, 1540552u, "5753d61be066d3818faaa9ca973f9ed5d01df6d4" },   /* Data/S3R/S3R.ins */
    { 136, 1, 788302u, "72479b59cf74e429bbb9f0b74b5013124f6bb41b" },   /* Data/S3R/S3R.rck */
    { 139, 1, 41808u, "21760415a6e940b1468b10c5ad052a96e82772c9" },   /* Data/SWS/code */
    { 140, 1, 87708u, "62ac17a9b10b6de425669e1bea3a16738bbdfa0a" },   /* Data/SWS/SWS.col */
    { 142, 1, 2897652u, "eedefee68e8ef663a947c2c04a0d398a81171650" },   /* Data/SWS/SWS.ins */
    { 143, 1, 603364u, "b285074394a2651ea8af24e230cf66c6015b8e28" },   /* Data/SWS/SWS.lit */
    { 144, 1, 2347390u, "fbc10cf805477bb2a4d134c3d0b6111d36ddc360" },   /* Data/SWS/SWS.rck */
    { 145, 1, 4176344u, "6bdc39933996c4a65f3415c48bb1131fc8bd9db1" },   /* Data/SWS/SWS.tex */
    { 147, 1, 68624u, "559f31b03e2e3437fd07a4dc4df00964d64c11fe" },   /* Data/W1A/code */
    { 150, 1, 3980016u, "39769f2a570e0239a3a6d67435740ed49183b268" },   /* Data/W1A/W1A.ins */
    { 152, 1, 2085378u, "1e35c491ed33a0516b00ba4546b1c4d32cfccace" },   /* Data/W1A/W1A.rck */
    { 158, 1, 4288788u, "1f129a6c2273e48f6d9c4c0cc03d52ce53b300c9" },   /* Data/W1B/W1B.ins */
    { 160, 1, 2085378u, "5fed82b93e8dde234a15cb9b7a6e78b1bec18938" },   /* Data/W1B/W1B.rck */
    { 166, 1, 3216120u, "82cf2181f857354eafde76d4b1f0911d5a7ee5bf" },   /* Data/W2A/W2A.ins */
    { 168, 1, 3154070u, "f4fd5a1f6cd66af20d069be76c153163afbb41d0" },   /* Data/W2A/W2A.rck */
    { 174, 1, 4256392u, "676bea6cb3beb062bd69ad3f41d4d7fe43fc997d" },   /* Data/W2B/W2B.ins */
    { 176, 1, 2316316u, "96644d997267f72522163f7572623e37912320f5" },   /* Data/W2B/W2B.rck */
    { 177, 1, 3533768u, "23e13c9da8dbdb31f4f74de750716bf272308634" },   /* Data/W2B/W2B.tex */
    { 182, 1, 4611164u, "c213904508e8887c99bad725845ca273293d20ab" },   /* Data/W2D/W2D.ins */
    { 184, 1, 2222622u, "aac64e51b84d437088b2ecdca57b4e1838568bd3" },   /* Data/W2D/W2D.rck */
    { 185, 1, 3422328u, "0dc72de015cac65e4973133cf037e999e6a6069a" },   /* Data/W2D/W2D.tex */
    { 190, 1, 3729940u, "ccc90410b970fd9ded2e074213e3110c353849cd" },   /* Data/W3A/W3A.ins */
    { 192, 1, 2107160u, "87b2a3405ddc81af5fbcc5aab2fbd5773cbdc681" },   /* Data/W3A/W3A.rck */
    { 198, 1, 4558668u, "ed540475e53fabc8a14ba5ed7b50c4c14c04afa3" },   /* Data/W3B/W3B.ins */
    { 200, 1, 1889010u, "4785e11fcc8c7fefc5a8b94899c15fcf2b37fef0" },   /* Data/W3B/W3B.rck */
    { 201, 1, 3746692u, "52241a67ace34121b1a5ece71045b90a04eca137" },   /* Data/W3B/W3B.tex */
    { 206, 1, 3196564u, "887b31c45370091dd6560ae5a693adb9b056ad40" },   /* Data/W3C/W3C.ins */
    { 208, 1, 2352782u, "0d76723a6db78187a48a356319884bc3c8d40dd2" },   /* Data/W3C/W3C.rck */
    { 212, 1, 113064u, "25ec4ecc02080e908426012c915ca0b4cf5bf790" },   /* Data/W3D/W3D.col */
    { 214, 1, 4923980u, "96ba91524cd86d40a465af69ea7b24ec0e266a9e" },   /* Data/W3D/W3D.ins */
    { 216, 1, 1895972u, "5d1dc34cb25ff0272e7f86c773ecbb0f7d0fd28d" },   /* Data/W3D/W3D.rck */
    { 219, 1, 66548u, "8655dca6c2a633ce3eacd1f441f0739317d68f5c" },   /* Data/WWS/code */
    { 220, 1, 96528u, "d13a5666440edbb8c1d9f1792c4020bedf0cad99" },   /* Data/WWS/WWS.col */
    { 222, 1, 4238880u, "7c190119893c99a77238b083cf10e1721c25ce41" },   /* Data/WWS/WWS.ins */
    { 223, 1, 603364u, "de25a32b73c19f69213a1cf3ba7ac8d3e89d4532" },   /* Data/WWS/WWS.lit */
    { 224, 1, 2342998u, "9d0356acf82a06729ca6c8ed993127f52b685e9a" },   /* Data/WWS/WWS.rck */
    { 225, 1, 3904900u, "efce09794aa671c4ba7f906e4c31b7a469bbc875" },   /* Data/WWS/WWS.tex */
    { 228, 1, 5358636u, "3634bcb03fb95d400e8dcd31c8975a57cf292774" },   /* Logo/Cryo.hnm */
    { 231, 1, 295553409u, "3fadce0a74f4159e775e8fbf387f8d5cdc16641d" },   /* Music.bf */
    { 0, 2, 5569792u, "0777d850dc52d1fc6007ef40d717ed21dedeb336" },   /* Common/Knothead.rck */
    { 1, 2, 5504218u, "6998d86bfd6332eddd67cb55eb199b414cd12976" },   /* Common/Splinter.rck */
    { 2, 2, 5756934u, "460d6d1655e835ef40c0ce1d1496f34163234275" },   /* Common/Woody.rck */
    { 7, 2, 6490998u, "b9c81bd0a0642f960fcef1675b023448c5284e2b" },   /* Data/Blackbox/Blackbox.rck */
    { 16, 2, 4074066u, "ae5457ff8a56158b2e31e5de4dad67164b49afed" },   /* Data/Credits/Credits.rck */
    { 22, 2, 7189676u, "d7dd6c97f5b6f13b6d44e097e5046a811ba10373" },   /* Data/House/House.ins */
    { 24, 2, 1378076u, "84ac1e8323dc997ac13fa26ca255519071e49a96" },   /* Data/House/House.rck */
    { 27, 2, 64136u, "0859b5de3426d9cce209a80448c27b9a101c876c" },   /* Data/K1A/code */
    { 28, 2, 79356u, "d0afd62bcf31ee2baf7e0ddc8275f71bdd6af89c" },   /* Data/K1A/K1A.col */
    { 30, 2, 2869404u, "7df363cb6202714407eb435178ec13f169a3ef2e" },   /* Data/K1A/K1A.ins */
    { 32, 2, 2085298u, "007e5f7697e794cb52806bbe363612a6b0a09e59" },   /* Data/K1A/K1A.rck */
    { 33, 2, 4081776u, "1bc9478a84d5acbebf0291fdbeb88527d09a0502" },   /* Data/K1A/K1A.tex */
    { 38, 2, 1088880u, "63badcfd880fc32db9fbf91ca0145a1346584c13" },   /* Data/K1R/K1R.ins */
    { 40, 2, 1045376u, "af7a60c9294aa61f71426316fbde11444b62a4c3" },   /* Data/K1R/K1R.rck */
    { 46, 2, 3057680u, "ccfd1b19e0048b8049fc50dfac17d8346bdc26ab" },   /* Data/K2A/K2A.ins */
    { 48, 2, 3153990u, "8f872343cb71de6bf568774542c1a1aa7e62ea26" },   /* Data/K2A/K2A.rck */
    { 54, 2, 1303436u, "84061465dae57d3a4136838138674834bbcaac78" },   /* Data/K2R/K2R.ins */
    { 56, 2, 1300408u, "45d1c72d830a27587f136e75f8baf7bf20f0cd76" },   /* Data/K2R/K2R.rck */
    { 62, 2, 3604092u, "bb0cf977a246cafb4115a070ef721b21156b02f7" },   /* Data/K3A/K3A.ins */
    { 64, 2, 2107080u, "7cdf65ee5d292638116e47baa208acaa7728c4b3" },   /* Data/K3A/K3A.rck */
    { 70, 2, 1778576u, "ac4210bb54f1d1c8016ca0b1c7e3ef8866856c3a" },   /* Data/K3R/K3R.ins */
    { 72, 2, 788222u, "13c642b54073540315fd16714966517ce5bab059" },   /* Data/K3R/K3R.rck */
    { 75, 2, 41984u, "6b15c35ac7062317afbcc3414d06ff2e81e23d74" },   /* Data/KWS/code */
    { 76, 2, 87664u, "d17a446526017eb9e7ab551b342ae07d80dd10e5" },   /* Data/KWS/KWS.col */
    { 78, 2, 2964184u, "c005be09ffe5015fd2a86b7929447e174461ea6f" },   /* Data/KWS/KWS.ins */
    { 79, 2, 603364u, "b285074394a2651ea8af24e230cf66c6015b8e28" },   /* Data/KWS/KWS.lit */
    { 80, 2, 2336686u, "728f9be563612dbd1592bc7f5737f995357ebf1b" },   /* Data/KWS/KWS.rck */
    { 81, 2, 4169788u, "73f4a7a245fb0ed0812722706e7ac87d61c0b4d7" },   /* Data/KWS/KWS.tex */
    { 88, 2, 1378124u, "b81ebfc2763d6d4ea0bd8af0820a673cda31d71e" },   /* Data/Lang/Lang.rck */
    { 89, 2, 43456u, "33b72d962ab489dbcc04dbdc01f8fdd6768d0a0c" },   /* Data/Lang/Lang.tex */
    { 91, 2, 69628u, "1d96e15158750b265c2b3a6e2f8dd0486f2f0754" },   /* Data/S1A/code */
    { 94, 2, 2874920u, "4dd591bd662fe6f36a7d361f6f18f63a18a15774" },   /* Data/S1A/S1A.ins */
    { 96, 2, 2085298u, "5429c67d67e5993e77a25d16f406e3f51421b085" },   /* Data/S1A/S1A.rck */
    { 102, 2, 1075088u, "d13bec7f00de798319e75792d910a54a290e7d26" },   /* Data/S1R/S1R.ins */
    { 104, 2, 1045376u, "7e868896bdf370e73830da3627459ecfeb23501e" },   /* Data/S1R/S1R.rck */
    { 110, 2, 2953396u, "697bfe06c259aed488e61c4d2a6b4439699c4c75" },   /* Data/S2A/S2A.ins */
    { 112, 2, 3153990u, "95cb17b57741d5a7400019d0f98d894a4566e5d7" },   /* Data/S2A/S2A.rck */
    { 118, 2, 1182320u, "6975af11183e84dc2d8d382e5a216c79cc51ba07" },   /* Data/S2R/S2R.ins */
    { 120, 2, 1300408u, "bd6ab86acf3215da2ad2a53de38c302d1abeb81a" },   /* Data/S2R/S2R.rck */
    { 126, 2, 3440176u, "f030f89b26a3683254e69068ed7d41c3013b3cd0" },   /* Data/S3A/S3A.ins */
    { 128, 2, 2107080u, "791451aad2a24b566a94598816affc023258608d" },   /* Data/S3A/S3A.rck */
    { 134, 2, 1540552u, "5753d61be066d3818faaa9ca973f9ed5d01df6d4" },   /* Data/S3R/S3R.ins */
    { 136, 2, 788222u, "6b52cf4eb797c27bcf8656bf8a3756a30cc6a92c" },   /* Data/S3R/S3R.rck */
    { 139, 2, 41808u, "21760415a6e940b1468b10c5ad052a96e82772c9" },   /* Data/SWS/code */
    { 140, 2, 87708u, "62ac17a9b10b6de425669e1bea3a16738bbdfa0a" },   /* Data/SWS/SWS.col */
    { 142, 2, 2897652u, "eedefee68e8ef663a947c2c04a0d398a81171650" },   /* Data/SWS/SWS.ins */
    { 143, 2, 603364u, "b285074394a2651ea8af24e230cf66c6015b8e28" },   /* Data/SWS/SWS.lit */
    { 144, 2, 2347310u, "5ca7325446cde65e939ad8038b696c8082f8174d" },   /* Data/SWS/SWS.rck */
    { 145, 2, 4176344u, "6bdc39933996c4a65f3415c48bb1131fc8bd9db1" },   /* Data/SWS/SWS.tex */
    { 147, 2, 68624u, "559f31b03e2e3437fd07a4dc4df00964d64c11fe" },   /* Data/W1A/code */
    { 150, 2, 3980016u, "39769f2a570e0239a3a6d67435740ed49183b268" },   /* Data/W1A/W1A.ins */
    { 152, 2, 2085298u, "e4031015d82b8f2c5b5677dc7609a79180eee4d1" },   /* Data/W1A/W1A.rck */
    { 158, 2, 4288788u, "1f129a6c2273e48f6d9c4c0cc03d52ce53b300c9" },   /* Data/W1B/W1B.ins */
    { 160, 2, 2085298u, "328abb5fcbf3add6d881986b28510227e1586bec" },   /* Data/W1B/W1B.rck */
    { 166, 2, 3216120u, "82cf2181f857354eafde76d4b1f0911d5a7ee5bf" },   /* Data/W2A/W2A.ins */
    { 168, 2, 3153990u, "b83491cbd62ac3b4dff75eac213596fd85b5c9b4" },   /* Data/W2A/W2A.rck */
    { 174, 2, 4256392u, "676bea6cb3beb062bd69ad3f41d4d7fe43fc997d" },   /* Data/W2B/W2B.ins */
    { 176, 2, 2316236u, "7d5e5c37ee303dd6203db882ddb1b2519c45f5e1" },   /* Data/W2B/W2B.rck */
    { 177, 2, 3533768u, "23e13c9da8dbdb31f4f74de750716bf272308634" },   /* Data/W2B/W2B.tex */
    { 182, 2, 4611164u, "c213904508e8887c99bad725845ca273293d20ab" },   /* Data/W2D/W2D.ins */
    { 184, 2, 2222542u, "245000a3b2f8b7aec5f3975bbfb1a3ff1ac6f299" },   /* Data/W2D/W2D.rck */
    { 185, 2, 3422328u, "0dc72de015cac65e4973133cf037e999e6a6069a" },   /* Data/W2D/W2D.tex */
    { 190, 2, 3729940u, "ccc90410b970fd9ded2e074213e3110c353849cd" },   /* Data/W3A/W3A.ins */
    { 192, 2, 2107080u, "e7502e4940dac08a26ea5ca28464a405edb860c5" },   /* Data/W3A/W3A.rck */
    { 198, 2, 4558668u, "ed540475e53fabc8a14ba5ed7b50c4c14c04afa3" },   /* Data/W3B/W3B.ins */
    { 200, 2, 1888930u, "7a8f34d5f1a484c7d5915d2d893c512de31a8fb6" },   /* Data/W3B/W3B.rck */
    { 201, 2, 3746692u, "52241a67ace34121b1a5ece71045b90a04eca137" },   /* Data/W3B/W3B.tex */
    { 206, 2, 3196564u, "887b31c45370091dd6560ae5a693adb9b056ad40" },   /* Data/W3C/W3C.ins */
    { 208, 2, 2352702u, "4a3eb4feae38318981a0d2a4b4f689a7c788be24" },   /* Data/W3C/W3C.rck */
    { 212, 2, 113064u, "25ec4ecc02080e908426012c915ca0b4cf5bf790" },   /* Data/W3D/W3D.col */
    { 214, 2, 4923980u, "96ba91524cd86d40a465af69ea7b24ec0e266a9e" },   /* Data/W3D/W3D.ins */
    { 216, 2, 1895892u, "6a6b61767b3251def76315202b7f703e60045414" },   /* Data/W3D/W3D.rck */
    { 219, 2, 66548u, "8655dca6c2a633ce3eacd1f441f0739317d68f5c" },   /* Data/WWS/code */
    { 220, 2, 96528u, "d13a5666440edbb8c1d9f1792c4020bedf0cad99" },   /* Data/WWS/WWS.col */
    { 222, 2, 4238880u, "7c190119893c99a77238b083cf10e1721c25ce41" },   /* Data/WWS/WWS.ins */
    { 223, 2, 603364u, "de25a32b73c19f69213a1cf3ba7ac8d3e89d4532" },   /* Data/WWS/WWS.lit */
    { 224, 2, 2342918u, "5545c110d3b715bbf1e1045518694f9e6ee29c3a" },   /* Data/WWS/WWS.rck */
    { 225, 2, 3904900u, "d324d97e640deed42de32592aaae71bdaf5ebb19" },   /* Data/WWS/WWS.tex */
    { 228, 2, 5358636u, "3634bcb03fb95d400e8dcd31c8975a57cf292774" },   /* Logo/Cryo.hnm */
    { 229, 2, 4939188u, "b399a74a88d9f61d89b7e55324b5d2977d107faa" },   /* Logo/Eko.hnm */
    { 231, 2, 295553409u, "9d8f1c9b693fd120e370484d06e2df4ac40ba7c2" },   /* Music.bf */
    { 0, 3, 5570932u, "14b156d945b05e0c53fd2f34a3f65ed5a3fe85ed" },   /* Common/Knothead.rck */
    { 1, 3, 5505358u, "26f395f55f7394d62b23d3cb592bb193c29d5522" },   /* Common/Splinter.rck */
    { 2, 3, 5758074u, "0e40b40b4455aa235cd4272c9a3692ba1597c9e7" },   /* Common/Woody.rck */
    { 7, 3, 6490978u, "df4ad892f6a84a3187721ae3a318301dc1042ea7" },   /* Data/Blackbox/Blackbox.rck */
    { 16, 3, 4074010u, "ce0104bb5e7b175fcb2dc784e0e624af3d833f1d" },   /* Data/Credits/Credits.rck */
    { 24, 3, 1378056u, "f2120600e3b1028fa5a10ec1a00bff75b8e4dc27" },   /* Data/House/House.rck */
    { 32, 3, 2085278u, "cd940d6631638a66979763edae14d0e0f9b63e39" },   /* Data/K1A/K1A.rck */
    { 40, 3, 1045356u, "80e5ac219ff16fe2baeba09952723f7d556d9fbb" },   /* Data/K1R/K1R.rck */
    { 48, 3, 3153970u, "4aa56a4cc1661c74d6cbdf7579b7cbad6afdcd00" },   /* Data/K2A/K2A.rck */
    { 56, 3, 1300388u, "21b8b860bb610b731ae6d5b03648107833d4ec86" },   /* Data/K2R/K2R.rck */
    { 64, 3, 2107060u, "8ee1d557bd2db9dd7055da18e9462127940e5d57" },   /* Data/K3A/K3A.rck */
    { 72, 3, 788202u, "0bf56ae384598caf05fd380bf3f47481e2550c83" },   /* Data/K3R/K3R.rck */
    { 80, 3, 2336666u, "0af0e3c4b9fab915beb69e22e387226e366f5712" },   /* Data/KWS/KWS.rck */
    { 88, 3, 1378104u, "c4c9308ff09337b2e54e6769ecab5cacd8741f02" },   /* Data/Lang/Lang.rck */
    { 96, 3, 2085278u, "b06f63c7e87606dc813f3b07781b28a15dcf3767" },   /* Data/S1A/S1A.rck */
    { 104, 3, 1045356u, "f72cf0a1ebe71716b92baa3e4b37b06c24b0fbfd" },   /* Data/S1R/S1R.rck */
    { 112, 3, 3153970u, "b1d941c8c185bd32eaefb9b097015aa37e870f5f" },   /* Data/S2A/S2A.rck */
    { 120, 3, 1300388u, "f071e1e39ece57fcee1fb3b47b33369d96d5604d" },   /* Data/S2R/S2R.rck */
    { 128, 3, 2107060u, "3578fcd6b7477c01a86a196dd73b9df2c4f59052" },   /* Data/S3A/S3A.rck */
    { 136, 3, 788202u, "2b151a4e561c7c157f4575ef55b89ff1dca2b90e" },   /* Data/S3R/S3R.rck */
    { 144, 3, 2347290u, "c43b7be819ec19bfb23a47b06963a3eaa229007e" },   /* Data/SWS/SWS.rck */
    { 152, 3, 2085278u, "9476a216b3103c4d98b4b18622bd4c2baa2ff134" },   /* Data/W1A/W1A.rck */
    { 160, 3, 2085278u, "75959518b80af07f7d940ea7a22528211a74c57f" },   /* Data/W1B/W1B.rck */
    { 168, 3, 3153970u, "de3f11401f803c509866eb19e79dc46a47e43878" },   /* Data/W2A/W2A.rck */
    { 176, 3, 2316216u, "fa536479b3d08151752452e06ca56fa8530f6fa8" },   /* Data/W2B/W2B.rck */
    { 184, 3, 2222522u, "8c31bb0b18372b33ca9329e36c956b0610eb7ff2" },   /* Data/W2D/W2D.rck */
    { 192, 3, 2107060u, "86d5fc0bae8a9325ebfd5aab69d695f5daef0d3d" },   /* Data/W3A/W3A.rck */
    { 200, 3, 1888910u, "da252b8db6051e1ae70638badc1d594396603325" },   /* Data/W3B/W3B.rck */
    { 208, 3, 2352682u, "8fc35477890350abe22f97c5e0cf350dd4a26733" },   /* Data/W3C/W3C.rck */
    { 216, 3, 1895872u, "d833a263ae34974da1a75b25f61828c70cd1b033" },   /* Data/W3D/W3D.rck */
    { 224, 3, 2342898u, "eddc5c80af084a1ca3a973b24551a4eba45c6d1a" },   /* Data/WWS/WWS.rck */
    { 228, 3, 5358636u, "3634bcb03fb95d400e8dcd31c8975a57cf292774" },   /* Logo/Cryo.hnm */
    { 229, 3, 2530432u, "006c814e9e70f26d6df6d4384dc41df915f90cd5" },   /* Logo/Eko.hnm */
    { 230, 3, 1428788u, "52a4a3e0a736d48a9175b315c685d375e592bfd3" },   /* Logo/Universal.hnm */
    { 0, 4, 5569822u, "a2275e83687592f96eb1023f7d2831f9ef1efbb8" },   /* Common/Knothead.rck */
    { 1, 4, 5504248u, "bf7197b4c33346e25d4696f7fb0aa90eafc05ee9" },   /* Common/Splinter.rck */
    { 2, 4, 5756964u, "046b1efbbef210c553aa680c9e551668a9e1804e" },   /* Common/Woody.rck */
    { 7, 4, 7016086u, "513f3fc097ef92be551f9f6fa73e59bc6c51ee9f" },   /* Data/Blackbox/Blackbox.rck */
    { 16, 4, 4337090u, "8fa2b47a2e3b46e1298bd4fa57995baf15f4cf81" },   /* Data/Credits/Credits.rck */
    { 22, 4, 7189676u, "d7dd6c97f5b6f13b6d44e097e5046a811ba10373" },   /* Data/House/House.ins */
    { 24, 4, 1903164u, "27567b960ebd976811387b186472b21aaa281e76" },   /* Data/House/House.rck */
    { 27, 4, 64136u, "0859b5de3426d9cce209a80448c27b9a101c876c" },   /* Data/K1A/code */
    { 28, 4, 79356u, "d0afd62bcf31ee2baf7e0ddc8275f71bdd6af89c" },   /* Data/K1A/K1A.col */
    { 30, 4, 2869404u, "7df363cb6202714407eb435178ec13f169a3ef2e" },   /* Data/K1A/K1A.ins */
    { 32, 4, 2610386u, "186a7bf1ea5f521b1ad942f5e87c2f3a1fe164ab" },   /* Data/K1A/K1A.rck */
    { 33, 4, 4081776u, "2dae7e5729b1e9db4419944028a2377036ccdcdb" },   /* Data/K1A/K1A.tex */
    { 38, 4, 1088880u, "63badcfd880fc32db9fbf91ca0145a1346584c13" },   /* Data/K1R/K1R.ins */
    { 40, 4, 1570464u, "67e859ca566150fb2879262a8f8770c764adaffc" },   /* Data/K1R/K1R.rck */
    { 46, 4, 3057680u, "ccfd1b19e0048b8049fc50dfac17d8346bdc26ab" },   /* Data/K2A/K2A.ins */
    { 48, 4, 3679078u, "76a9b4b6bc0c6e3bf7e57f87d6b55a823d6c3740" },   /* Data/K2A/K2A.rck */
    { 54, 4, 1303436u, "84061465dae57d3a4136838138674834bbcaac78" },   /* Data/K2R/K2R.ins */
    { 56, 4, 1825496u, "c8984b527aa7fd8616b9bb72ad0c58fec467f726" },   /* Data/K2R/K2R.rck */
    { 62, 4, 3604092u, "bb0cf977a246cafb4115a070ef721b21156b02f7" },   /* Data/K3A/K3A.ins */
    { 64, 4, 2632168u, "02a7872f7a159fbdf61506e86ded5fdbeca00dce" },   /* Data/K3A/K3A.rck */
    { 70, 4, 1778576u, "ac4210bb54f1d1c8016ca0b1c7e3ef8866856c3a" },   /* Data/K3R/K3R.ins */
    { 72, 4, 1313310u, "acc7faa049f2971ee934ae759ad37579245c203d" },   /* Data/K3R/K3R.rck */
    { 75, 4, 41984u, "6b15c35ac7062317afbcc3414d06ff2e81e23d74" },   /* Data/KWS/code */
    { 76, 4, 87664u, "d17a446526017eb9e7ab551b342ae07d80dd10e5" },   /* Data/KWS/KWS.col */
    { 78, 4, 2964184u, "c005be09ffe5015fd2a86b7929447e174461ea6f" },   /* Data/KWS/KWS.ins */
    { 79, 4, 603364u, "b285074394a2651ea8af24e230cf66c6015b8e28" },   /* Data/KWS/KWS.lit */
    { 80, 4, 2861774u, "73a5b9058f239d31832e466e654cfff885c437d2" },   /* Data/KWS/KWS.rck */
    { 81, 4, 4169788u, "73f4a7a245fb0ed0812722706e7ac87d61c0b4d7" },   /* Data/KWS/KWS.tex */
    { 83, 4, 0u, "" },   /* Data/Lang/code */
    { 84, 4, 0u, "" },   /* Data/Lang/Lang.col */
    { 85, 4, 0u, "" },   /* Data/Lang/Lang.gel */
    { 86, 4, 0u, "" },   /* Data/Lang/Lang.ins */
    { 87, 4, 0u, "" },   /* Data/Lang/Lang.lit */
    { 88, 4, 0u, "" },   /* Data/Lang/Lang.rck */
    { 89, 4, 0u, "" },   /* Data/Lang/Lang.tex */
    { 90, 4, 0u, "" },   /* Data/Lang/Lang.vis */
    { 91, 4, 69628u, "1d96e15158750b265c2b3a6e2f8dd0486f2f0754" },   /* Data/S1A/code */
    { 94, 4, 2874920u, "4dd591bd662fe6f36a7d361f6f18f63a18a15774" },   /* Data/S1A/S1A.ins */
    { 96, 4, 2610386u, "c0477c58f60039f4855cc3f69c39e8eec818beac" },   /* Data/S1A/S1A.rck */
    { 102, 4, 1075088u, "d13bec7f00de798319e75792d910a54a290e7d26" },   /* Data/S1R/S1R.ins */
    { 104, 4, 1570464u, "664147eda9903b2b506b1f8b118fdd112fe8edbe" },   /* Data/S1R/S1R.rck */
    { 110, 4, 2953396u, "697bfe06c259aed488e61c4d2a6b4439699c4c75" },   /* Data/S2A/S2A.ins */
    { 112, 4, 3679078u, "64ba8c04fbd625e5371b567b6fcd79c0c20c0ea9" },   /* Data/S2A/S2A.rck */
    { 118, 4, 1182320u, "6975af11183e84dc2d8d382e5a216c79cc51ba07" },   /* Data/S2R/S2R.ins */
    { 120, 4, 1825496u, "d785dd5d8fff1980bdd141b040b0b0db36cce0bb" },   /* Data/S2R/S2R.rck */
    { 126, 4, 3440176u, "f030f89b26a3683254e69068ed7d41c3013b3cd0" },   /* Data/S3A/S3A.ins */
    { 128, 4, 2632168u, "d0da1368907c443258b163333bdc53dc53cbb953" },   /* Data/S3A/S3A.rck */
    { 134, 4, 1540552u, "5753d61be066d3818faaa9ca973f9ed5d01df6d4" },   /* Data/S3R/S3R.ins */
    { 136, 4, 1313310u, "70033d23416e6483809298baac39d60b03445c28" },   /* Data/S3R/S3R.rck */
    { 139, 4, 41808u, "21760415a6e940b1468b10c5ad052a96e82772c9" },   /* Data/SWS/code */
    { 140, 4, 87708u, "62ac17a9b10b6de425669e1bea3a16738bbdfa0a" },   /* Data/SWS/SWS.col */
    { 142, 4, 2897652u, "eedefee68e8ef663a947c2c04a0d398a81171650" },   /* Data/SWS/SWS.ins */
    { 143, 4, 603364u, "b285074394a2651ea8af24e230cf66c6015b8e28" },   /* Data/SWS/SWS.lit */
    { 144, 4, 2872398u, "4783137133a39ed502b443fb4f379e2f895970dc" },   /* Data/SWS/SWS.rck */
    { 145, 4, 4176344u, "6bdc39933996c4a65f3415c48bb1131fc8bd9db1" },   /* Data/SWS/SWS.tex */
    { 147, 4, 68624u, "559f31b03e2e3437fd07a4dc4df00964d64c11fe" },   /* Data/W1A/code */
    { 150, 4, 3980016u, "39769f2a570e0239a3a6d67435740ed49183b268" },   /* Data/W1A/W1A.ins */
    { 152, 4, 2610386u, "0bcc6abd8a55e5c8414c3dfb350e25e56ae2343b" },   /* Data/W1A/W1A.rck */
    { 158, 4, 4288788u, "1f129a6c2273e48f6d9c4c0cc03d52ce53b300c9" },   /* Data/W1B/W1B.ins */
    { 160, 4, 2610386u, "e0b7741deeb3ec5bf8fecbfb27e0283c9d100e26" },   /* Data/W1B/W1B.rck */
    { 166, 4, 3216120u, "82cf2181f857354eafde76d4b1f0911d5a7ee5bf" },   /* Data/W2A/W2A.ins */
    { 168, 4, 3679078u, "f2b31922a8e112fb23936d3fdbe3f243bb74de3e" },   /* Data/W2A/W2A.rck */
    { 174, 4, 4256392u, "676bea6cb3beb062bd69ad3f41d4d7fe43fc997d" },   /* Data/W2B/W2B.ins */
    { 176, 4, 2841324u, "63b8cad643c0d03ce55395ecd0792fb68bce5a36" },   /* Data/W2B/W2B.rck */
    { 177, 4, 3533768u, "23e13c9da8dbdb31f4f74de750716bf272308634" },   /* Data/W2B/W2B.tex */
    { 182, 4, 4611164u, "c213904508e8887c99bad725845ca273293d20ab" },   /* Data/W2D/W2D.ins */
    { 184, 4, 2747630u, "ef02b2e9dbba4febf6c2cd9c758bd069fe237cbe" },   /* Data/W2D/W2D.rck */
    { 185, 4, 3422328u, "0dc72de015cac65e4973133cf037e999e6a6069a" },   /* Data/W2D/W2D.tex */
    { 190, 4, 3729940u, "ccc90410b970fd9ded2e074213e3110c353849cd" },   /* Data/W3A/W3A.ins */
    { 192, 4, 2632168u, "2f8c340f4d83b70cea45f4b8f433565e8168ae0c" },   /* Data/W3A/W3A.rck */
    { 198, 4, 4558668u, "ed540475e53fabc8a14ba5ed7b50c4c14c04afa3" },   /* Data/W3B/W3B.ins */
    { 200, 4, 2414018u, "f731178d15af3df29a6e3ea8f80e9e15085a19bd" },   /* Data/W3B/W3B.rck */
    { 201, 4, 3746692u, "52241a67ace34121b1a5ece71045b90a04eca137" },   /* Data/W3B/W3B.tex */
    { 206, 4, 3196564u, "887b31c45370091dd6560ae5a693adb9b056ad40" },   /* Data/W3C/W3C.ins */
    { 208, 4, 2877790u, "45ba3a8569eb85a8a1138d3eff49b84b32900bdc" },   /* Data/W3C/W3C.rck */
    { 212, 4, 113064u, "25ec4ecc02080e908426012c915ca0b4cf5bf790" },   /* Data/W3D/W3D.col */
    { 214, 4, 4923980u, "96ba91524cd86d40a465af69ea7b24ec0e266a9e" },   /* Data/W3D/W3D.ins */
    { 216, 4, 2420980u, "861130646989583663810c95702e04c8ee997e6b" },   /* Data/W3D/W3D.rck */
    { 219, 4, 66548u, "8655dca6c2a633ce3eacd1f441f0739317d68f5c" },   /* Data/WWS/code */
    { 220, 4, 96528u, "d13a5666440edbb8c1d9f1792c4020bedf0cad99" },   /* Data/WWS/WWS.col */
    { 222, 4, 4238880u, "7c190119893c99a77238b083cf10e1721c25ce41" },   /* Data/WWS/WWS.ins */
    { 223, 4, 603364u, "de25a32b73c19f69213a1cf3ba7ac8d3e89d4532" },   /* Data/WWS/WWS.lit */
    { 224, 4, 2868006u, "a1d5f586bbed5d990b066a1e0a5fd6a1efd65740" },   /* Data/WWS/WWS.rck */
    { 225, 4, 3904900u, "efce09794aa671c4ba7f906e4c31b7a469bbc875" },   /* Data/WWS/WWS.tex */
    { 228, 4, 5358636u, "3634bcb03fb95d400e8dcd31c8975a57cf292774" },   /* Logo/Cryo.hnm */
    { 229, 4, 7332008u, "813f5ee7d9147aeb121db37648a283776d2560fc" },   /* Logo/Eko.hnm */
    { 231, 4, 295553409u, "3fadce0a74f4159e775e8fbf387f8d5cdc16641d" },   /* Music.bf */
};
/* checks manifest file i (sha1 NULL = by size only): 1 when it is the copy of any supported release, 0 if none. Adds 1 to
 * fit[r] for every release r whose copy it is, so the release a whole copy came from = the r with the highest fit[r]
 * (datafile_best). A release's copy = its k_datafiles_alt entry, or the English file when it has none; an entry with an
 * empty SHA-1 = the release has no such file. */
static int datafile_tally(int i, unsigned long long size, const char *sha1, int *fit)
{
    int any = 0;
    for (int r = 0; r < DATAFILES_RELEASES; r++) {
        unsigned sz = k_datafiles[i].size; const char *h = k_datafiles[i].sha1;
        for (int k = 0; k < DATAFILES_ALT; k++) if (k_datafiles_alt[k].file == i && k_datafiles_alt[k].release == r) { sz = k_datafiles_alt[k].size; h = k_datafiles_alt[k].sha1; }
        if (*h && size == sz && (!sha1 || !strcmp(sha1, h))) { any = 1; if (fit) fit[r]++; }
    }
    return any;
}
/* manifest file i is missing: 1 when a supported release has no such file either (adds 1 to fit[r] for each), 0 if all have it */
static int datafile_absent(int i, int *fit)
{
    int any = 0;
    for (int k = 0; k < DATAFILES_ALT; k++) if (k_datafiles_alt[k].file == i && !*k_datafiles_alt[k].sha1) { any = 1; if (fit) fit[k_datafiles_alt[k].release]++; }
    return any;
}
static int datafile_best(const int *fit) { int b = 0; for (int r = 1; r < DATAFILES_RELEASES; r++) if (fit[r] > fit[b]) b = r; return b; }
