/* datasetup.c - where the game data comes from (PORT EXTRA, datasetup.h). The original installs only its exe and DLLs and reads
 * Data\, Common\, Logo\, Game\ and Music.bf from the CD; the port wants a copy of those five on disk. At the first start it looks
 * for the CD (or a mounted ISO image) in every drive, copies the 232 files of the manifest (src/datafiles.h, generated by
 * tools/mkmanifest.py from the English 1.00 CD) into data\ and checks their SHA-1 on the way. Paths here are wide (the exe may
 * sit under a user name the ANSI code page cannot spell); the engine only ever sees "data\Data" relative to the folder this
 * makes current. */
#include "datasetup.h"
#include "datafiles.h"
#include <windows.h>
#include <shlobj.h>
#include <bcrypt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

#define TITLE L"WoodyRE"
#define WPATH (MAX_PATH * 2)

static int exists(const wchar_t *p) { return GetFileAttributesW(p) != INVALID_FILE_ATTRIBUTES; }

/* root (no trailing backslash, a drive is "E:") has the CD layout */
static int cd_layout(const wchar_t *root)
{
    static const wchar_t *probe[3] = { L"Data\\W1A\\W1A.gel", L"Common\\Woody.rck", L"Music.bf" };   /* Music.bf is copied last */
    wchar_t p[WPATH];
    for (int i = 0; i < 3; i++) { swprintf(p, WPATH, L"%ls\\%ls", root, probe[i]); if (!exists(p)) return 0; }
    return 1;
}

static void exe_dir(wchar_t *d)
{
    DWORD n = GetModuleFileNameW(NULL, d, MAX_PATH); if (!n || n >= MAX_PATH) { wcscpy(d, L"."); return; }
    wchar_t *s = wcsrchr(d, L'\\'); if (s) *s = 0;
}

static int local_dir(wchar_t *d)                       /* %LOCALAPPDATA%\WoodyRE (not created here) */
{
    DWORD n = GetEnvironmentVariableW(L"LOCALAPPDATA", d, MAX_PATH);
    if (!n || n >= MAX_PATH - 16) return 0;
    wcscat(d, L"\\WoodyRE"); return 1;
}

static int writable(const wchar_t *dir)
{
    wchar_t p[WPATH]; swprintf(p, WPATH, L"%ls\\woodyre.tmp", dir);
    HANDLE h = CreateFileW(p, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_FLAG_DELETE_ON_CLOSE, NULL);
    if (h == INVALID_HANDLE_VALUE) return 0;
    CloseHandle(h); return 1;
}

static const char *enter(const wchar_t *home, const char *rel)
{
    if (!SetCurrentDirectoryW(home)) return NULL;
    return rel;
}

static void make_dirs(wchar_t *path)                   /* creates every parent directory of path */
{
    for (wchar_t *p = path; *p; p++) if (*p == L'\\' && p > path + 2) { *p = 0; CreateDirectoryW(path, NULL); *p = L'\\'; }
}

static void rel_path(wchar_t *out, const wchar_t *root, const char *rel)
{
    int n = swprintf(out, WPATH, L"%ls\\", root);
    for (const char *c = rel; *c && n < WPATH - 1; c++) out[n++] = *c == '/' ? L'\\' : (wchar_t)(unsigned char)*c;
    out[n] = 0;
}

/* ---- progress window (same look as the standalone launcher, tools/native/bundle.c) ---- */
static HWND g_win, g_text;
static unsigned long long g_done, g_total;

static void pump(void) { MSG m; while (PeekMessageW(&m, NULL, 0, 0, PM_REMOVE)) { TranslateMessage(&m); DispatchMessageW(&m); } }

static void progress_show(void)
{
    g_win = CreateWindowExW(WS_EX_TOPMOST, L"STATIC", TITLE, WS_POPUP | WS_BORDER | WS_VISIBLE,
                            (GetSystemMetrics(SM_CXSCREEN) - 460) / 2, (GetSystemMetrics(SM_CYSCREEN) - 70) / 2, 460, 70, NULL, NULL, NULL, NULL);
    g_text = CreateWindowExW(0, L"STATIC", L"", WS_CHILD | WS_VISIBLE | SS_CENTER | SS_CENTERIMAGE, 0, 0, 460, 70, g_win, NULL, NULL, NULL);
    SendMessageW(g_text, WM_SETFONT, (WPARAM)GetStockObject(DEFAULT_GUI_FONT), 0);
    pump();
}

static void progress(void)
{
    static int last = -1; int pct = g_total ? (int)(g_done * 100 / g_total) : 100;
    if (pct == last || !g_text) return; last = pct;
    wchar_t s[128]; swprintf(s, 128, L"Copying the game files from the CD (first start only)... %d%%", pct);
    SetWindowTextW(g_text, s); pump();
}

/* ---- SHA-1 (Windows CNG) ---- */
static BCRYPT_ALG_HANDLE g_alg;
static int g_fit[DATAFILES_RELEASES];   /* per supported release: how many files of the last copy/verify were its copy (datafile_tally) */

/* reads one manifest file under src_root, writes it to dst_root when that is set (as name.part, renamed at the end) and compares
 * its SHA-1: 1 = equal, 2 = missing as in a supported release, 0 = differs, -1 = missing (src) or cannot be written (dst) */
static int file_pass(const wchar_t *src_root, const wchar_t *dst_root, int i, unsigned char *buf, DWORD bufsz)
{
    wchar_t sp[WPATH], dp[WPATH], tp[WPATH + 8];
    rel_path(sp, src_root, k_datafiles[i].path);
    HANDLE s = CreateFileW(sp, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_FLAG_SEQUENTIAL_SCAN, NULL);
    if (s == INVALID_HANDLE_VALUE) return datafile_absent(i, g_fit) ? 2 : -1;   /* the Russian CD has no Data/Lang (never read on the PC) */
    HANDLE d = INVALID_HANDLE_VALUE;
    if (dst_root) {
        rel_path(dp, dst_root, k_datafiles[i].path); make_dirs(dp); swprintf(tp, WPATH + 8, L"%ls.part", dp);
        d = CreateFileW(tp, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
        if (d == INVALID_HANDLE_VALUE) { CloseHandle(s); return -1; }
    }
    BCRYPT_HASH_HANDLE h = NULL;
    if (!g_alg && !BCRYPT_SUCCESS(BCryptOpenAlgorithmProvider(&g_alg, BCRYPT_SHA1_ALGORITHM, NULL, 0))) g_alg = NULL;
    if (g_alg && !BCRYPT_SUCCESS(BCryptCreateHash(g_alg, &h, NULL, 0, NULL, 0, 0))) h = NULL;
    int ok = 1; unsigned long long size = 0; DWORD got, put;
    while (ReadFile(s, buf, bufsz, &got, NULL) && got) {
        if (h) BCryptHashData(h, buf, got, 0);
        if (d != INVALID_HANDLE_VALUE && (!WriteFile(d, buf, got, &put, NULL) || put != got)) { ok = -1; break; }
        size += got; g_done += got; progress();
    }
    CloseHandle(s);
    char hex[41] = "";
    if (h) { UCHAR dig[20]; BCryptFinishHash(h, dig, 20, 0); BCryptDestroyHash(h); for (int k = 0; k < 20; k++) sprintf(hex + 2 * k, "%02x", dig[k]); }
    if (ok > 0 && !datafile_tally(i, size, h ? hex : NULL, g_fit)) ok = 0;
    if (d != INVALID_HANDLE_VALUE) {
        if (!CloseHandle(d) || ok < 0 || !MoveFileExW(tp, dp, MOVEFILE_REPLACE_EXISTING)) { DeleteFileW(tp); return -1; }
    }
    return ok;
}

/* copies the manifest from src (CD layout) into <home>\data. Returns the number of files that match no supported release, -1 = failed */
static int copy_cd(const wchar_t *src, const wchar_t *home)
{
    wchar_t dst[WPATH]; swprintf(dst, WPATH, L"%ls\\data", home); CreateDirectoryW(dst, NULL);
    ULARGE_INTEGER freeb;
    if (GetDiskFreeSpaceExW(home, &freeb, NULL, NULL) && freeb.QuadPart < (unsigned long long)DATAFILES_BYTES + (16u << 20)) {
        wchar_t m[WPATH + 200]; swprintf(m, WPATH + 200, L"Not enough free disk space for the game files (%u MB) in\n%ls", DATAFILES_BYTES >> 20, dst);
        MessageBoxW(NULL, m, TITLE, MB_ICONERROR); return -1;
    }
    DWORD bufsz = 4u << 20; unsigned char *buf = malloc(bufsz); if (!buf) return -1;
    g_done = 0; g_total = DATAFILES_BYTES; progress_show(); progress();
    int bad = 0, first_bad = -1; memset(g_fit, 0, sizeof g_fit);
    for (int i = 0; i < DATAFILES_COUNT; i++) {
        int r = file_pass(src, dst, i, buf, bufsz);
        if (r < 0) {
            if (g_win) { DestroyWindow(g_win); g_win = g_text = NULL; }
            wchar_t m[WPATH + 400]; swprintf(m, WPATH + 400, L"Could not copy %hs\nfrom %ls\\ to\n%ls\\\n\nIs the CD complete, and is there room on the disk?\n"
                                                             L"(WoodyRE supports the English 1.00, Brazilian, Polish, Spanish and Russian CDs.)", k_datafiles[i].path, src, dst);
            MessageBoxW(NULL, m, TITLE, MB_ICONERROR); free(buf); return -1;
        }
        if (!r) { bad++; if (first_bad < 0) first_bad = i; printf("data: %s matches none of the supported CDs\n", k_datafiles[i].path); }
    }
    free(buf);
    if (g_win) { DestroyWindow(g_win); g_win = g_text = NULL; }
    printf("data: copied from the %s CD\n", k_releases[datafile_best(g_fit)]);
    if (bad) {
        wchar_t m[512]; swprintf(m, 512, L"%d of the copied files match none of the supported CDs (the first: %hs).\n\n"
                                         L"WoodyRE supports the English 1.00, Brazilian, Polish, Spanish and Russian CDs; another release or a damaged copy may not work correctly.", bad, k_datafiles[first_bad].path);
        MessageBoxW(NULL, m, TITLE, MB_ICONWARNING);
    }
    return bad;
}

static int find_cd(wchar_t *root)                      /* any drive with the CD layout (a real CD or a mounted ISO image) */
{
    DWORD drives = GetLogicalDrives();
    for (int l = 2; l < 26; l++) {                      /* C: .. Z: */
        if (!(drives >> l & 1)) continue;
        swprintf(root, 4, L"%lc:", L'A' + l);
        if (cd_layout(root)) return 1;
    }
    return 0;
}

static int pick_folder(wchar_t *root)
{
    int ok = 0; HRESULT co = CoInitializeEx(NULL, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE);
    BROWSEINFOW bi; memset(&bi, 0, sizeof bi);
    bi.lpszTitle = L"Choose the folder that holds the CD's files (Data, Common, Logo, Game, Music.bf):";
    bi.ulFlags = BIF_RETURNONLYFSDIRS | BIF_NEWDIALOGSTYLE | BIF_NONEWFOLDERBUTTON;
    PIDLIST_ABSOLUTE id = SHBrowseForFolderW(&bi);
    if (id) { ok = SHGetPathFromIDListW(id, root) != 0; CoTaskMemFree(id); }
    if (SUCCEEDED(co)) CoUninitialize();
    size_t n = wcslen(root); if (ok && n && root[n - 1] == L'\\') root[n - 1] = 0;
    return ok;
}

/* the exe's folder can hold what the game writes: not read-only (Program Files) and not under %TEMP%, where Explorer runs an
 * exe started from inside a zip and where the files would not last */
static int home_ok(const wchar_t *dir)
{
    wchar_t t[MAX_PATH + 1], d[WPATH]; DWORD n = GetTempPathW(MAX_PATH + 1, t);   /* t ends with a backslash */
    swprintf(d, WPATH, L"%ls\\", dir);
    if (n > 3 && n <= MAX_PATH && t[n - 1] == L'\\' && !_wcsnicmp(d, t, n)) return 0;   /* (not a TEMP that is a whole drive) */
    return writable(dir);
}

/* the game files in dir\rel, but dir is no place for woodyre.cfg / .sav / .log and mods\: those go to %LOCALAPPDATA%\WoodyRE,
 * which becomes the current directory, and the engine reads the files by their full path (an ANSI one: its fopen is
 * ANSI; the 8.3 name when the code page cannot spell the long one). NULL = not possible, the caller enters dir instead. */
static const char *enter_away(const wchar_t *dir, const wchar_t *rel, const wchar_t *local)
{
    static char out[WPATH]; wchar_t full[WPATH], s[WPATH]; BOOL bad = FALSE;
    int utf8 = GetACP() == CP_UTF8;                    /* "Beta: Unicode UTF-8" region setting: every name fits, and the flags must be 0 */
    swprintf(full, WPATH, L"%ls\\%ls", dir, rel);
    if (!WideCharToMultiByte(CP_ACP, utf8 ? 0 : WC_NO_BEST_FIT_CHARS, full, -1, out, sizeof out, NULL, utf8 ? NULL : &bad) || bad) {
        DWORD k = GetShortPathNameW(full, s, WPATH); bad = FALSE;
        if (!k || k >= WPATH || !WideCharToMultiByte(CP_ACP, utf8 ? 0 : WC_NO_BEST_FIT_CHARS, s, -1, out, sizeof out, NULL, utf8 ? NULL : &bad) || bad) return NULL;
    }
    CreateDirectoryW(local, NULL);
    return SetCurrentDirectoryW(local) ? out : NULL;
}

const char *data_find(void)
{
    const char *env = getenv("WOODY_DATA"); if (env && *env) return env;
    wchar_t exe[MAX_PATH], local[MAX_PATH], p[WPATH];
    exe_dir(exe);
    int have_local = local_dir(local), exe_ok = home_ok(exe);
    const char *r;
    swprintf(p, WPATH, L"%ls\\data", exe);
    if (cd_layout(p)) return !exe_ok && have_local && (r = enter_away(exe, L"data\\Data", local)) ? r : enter(exe, "data\\Data");
    if (cd_layout(exe)) return !exe_ok && have_local && (r = enter_away(exe, L"Data", local)) ? r : enter(exe, "Data");
    if (cd_layout(L"extract")) return "extract/Data";
    if (have_local) { swprintf(p, WPATH, L"%ls\\data", local); if (cd_layout(p)) return enter(local, "data\\Data"); }

    /* first start: copy the CD into data\ next to the exe, or under %LOCALAPPDATA% when that folder is read-only (or temporary) */
    const wchar_t *home = exe;
    if (!exe_ok && have_local) { CreateDirectoryW(local, NULL); home = local; }
    else if (!exe_ok && !writable(exe)) { MessageBoxW(NULL, L"No writable folder for the game files.", TITLE, MB_ICONERROR); return NULL; }
    UINT em = SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX);   /* no "insert a disk" boxes while probing drives */
    const char *res = NULL;
    for (;;) {
        wchar_t src[MAX_PATH] = L"", m[WPATH + 600]; int r;
        if (find_cd(src)) {
            swprintf(m, WPATH + 600, L"Found the Woody Woodpecker CD in drive %ls\n\nCopy its game files (%u MB) to\n%ls\\data ?\n\n"
                                     L"This happens once; afterwards the CD is not needed.\n(No = choose another folder instead)", src, DATAFILES_BYTES >> 20, home);
            r = MessageBoxW(NULL, m, TITLE, MB_YESNOCANCEL | MB_ICONQUESTION);
            if (r == IDCANCEL) break;
            if (r == IDNO && !pick_folder(src)) continue;
        } else {
            r = MessageBoxW(NULL, L"WoodyRE needs the files of the original game CD-ROM:\n"
                                  L"Woody Woodpecker: Escape from Buzz Buzzard Park (PC; the English, Brazilian, Polish, Spanish or Russian CD).\n\n"
                                  L"Insert the CD or mount your ISO image of it, then press Yes to search again.\n"
                                  L"Press No to choose a folder that holds a copy of the CD's files instead.", TITLE, MB_YESNOCANCEL | MB_ICONINFORMATION);
            if (r == IDCANCEL) break;
            if (r == IDYES || !pick_folder(src)) continue;
        }
        if (!cd_layout(src)) {
            swprintf(m, WPATH + 600, L"%ls\\ does not hold the game's files (Data, Common, Logo, Game and Music.bf from the CD).", src);
            MessageBoxW(NULL, m, TITLE, MB_ICONWARNING); continue;
        }
        if (copy_cd(src, home) < 0) break;
        res = enter(home, "data\\Data");
        break;
    }
    SetErrorMode(em);
    return res;
}

int data_verify(const char *data_dir)
{
    wchar_t root[WPATH]; char r[MAX_PATH + 8];
    snprintf(r, sizeof r, "%s\\..", data_dir);
    if (!MultiByteToWideChar(CP_ACP, 0, r, -1, root, WPATH)) return -1;
    DWORD bufsz = 4u << 20; unsigned char *buf = malloc(bufsz); if (!buf) return -1;
    int bad = 0; memset(g_fit, 0, sizeof g_fit);
    for (int i = 0; i < DATAFILES_COUNT; i++) {
        int k = file_pass(root, NULL, i, buf, bufsz);
        if (k <= 0) { bad++; printf("verify: %s %s\n", k_datafiles[i].path, k < 0 ? "MISSING" : "matches none of the supported CDs"); }
    }
    free(buf);
    int best = datafile_best(g_fit);
    printf("verify: %d of %d files belong to a supported CD; the copy is the %s CD (%d of its files)%s\n", DATAFILES_COUNT - bad, DATAFILES_COUNT,
           k_releases[best], g_fit[best], bad ? "" : " - all good");
    return bad;
}
